version: '3'
services:
  app:
    container_name: trex-todo
    build: .
    ports:
      - "8080:8080"
    restart: unless-stopped
  db:
    image: mongo
    container_name: test-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=michael
      - MONGO_INITDB_ROOT_PASSWORD=secret